# Generated by Django 4.2 on 2023-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="boardmembership",
            constraint=models.UniqueConstraint(
                fields=("board", "user"), name="one_membership_per_user_per_board"
            ),
        ),
    ]
