# Generated by Django 4.2 on 2023-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_boardmembership_one_membership_per_user_per_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
